StudentManagementSystem/Controllers/CourcesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.DataAcess.Interface;
using StudentManagementSystem.DataAcess.Repository;
using StudentManagementSystem.ViewModels;
using System.Threading.Tasks;

namespace StudentManagementSystem.Controllers
{
    [Authorize]
    public class CourcesController : Controller
    {
        private readonly ICourcesInterface _courcesRepository;

        public CourcesController(ICourcesInterface courcesRepository)
        {
            _courcesRepository = courcesRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var allCources = _courcesRepository.GetAllCources();
            return View(allCources);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CourcesViewModel cources)
        {
            if (ModelState.IsValid)
            {
                _courcesRepository.Create(cources);
                return RedirectToAction("Index");
            }
            return View(cources);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var courceViewModel = _courcesRepository.GetCources(id);
            if (courceViewModel == null)
            {
                return NotFound();
            }
            return View(courceViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CourcesViewModel courcesViewModel)
        {
            if (ModelState.IsValid)
            {
                _courcesRepository.Edit(courcesViewModel);
                return RedirectToAction("Index");
            }
            return View(courcesViewModel);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var courceViewModel = _courcesRepository.GetCources(id);
            if (courceViewModel == null)
            {
                return NotFound();
            }
            return View(courceViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _courcesRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

StudentManagementSystem/Controllers/FacultyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using StudentManagementSystem.Data;
using StudentManagementSystem.DataAcess.Interface;
using StudentManagementSystem.DataAcess.Repository;
using StudentManagementSystem.ViewModels;
using System.Threading.Tasks;

namespace StudentManagementSystem.Controllers
{
    [Authorize]
    public class FacultyController : Controller
    {
        private readonly IFacultyInterface _fr;

        public FacultyController(IFacultyInterface fr)
        {
            _fr = fr;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var allFaculty = _fr.GetAllFaculty();
            return View(allFaculty);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FacultyViewModel faculty)
        {
            if (ModelState.IsValid)
            {
                _fr.Create(faculty);
                return RedirectToAction("Index");
            }
            return View(faculty);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var facultyViewModel = _fr.GetFaculty(id);
            if (facultyViewModel != null)
            {
                return View(facultyViewModel);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(FacultyViewModel facultyViewModel)
        {
           if (ModelState.IsValid)
            {
                _fr.Edit(facultyViewModel);
                return RedirectToAction("Index");
            }
           return View(facultyViewModel);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var facultyViewModel = _fr.GetFaculty(id);
            if (facultyViewModel == null)
            {
                return NotFound();
            }
            return View(facultyViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _fr.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

StudentManagementSystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.Models;
using System.Diagnostics;

namespace StudentManagementSystem.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StudentManagementSystem/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol;
using StudentManagementSystem.Data;
using StudentManagementSystem.DataAcess.Interface;
using StudentManagementSystem.DataAcess.Repository;
using StudentManagementSystem.Models;
using StudentManagementSystem.ViewModels;

namespace StudentManagementSystem.Controllers
{
    [Authorize]

    public class StudentController : Controller
    {
        private readonly IStudentInterface _tr;

        public StudentController(IStudentInterface db)
        {
            _tr = db;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var allstudents = _tr.GetAllStudents();
            return View(allstudents);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create( StudentViewModel student)
        {

            
            if (ModelState.IsValid)
            {
                _tr.Create(student);
                return View("Index");

            }
            return View(student);
           
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var studentViewModel = _tr.GetStudent(id);
            if (studentViewModel != null)
            {
                return View(studentViewModel);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StudentViewModel studentViewModel)
        {
            if (ModelState.IsValid)
            {
               
                _tr.Edit(studentViewModel);
                return RedirectToAction("Index");
            }
            return View(studentViewModel);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var student = _tr.GetStudent(id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConform(int id)
        {
            _tr.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

StudentManagementSystem/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.DataAcess.Interface;
using StudentManagementSystem.DataAcess.Repository;
using StudentManagementSystem.Models;

namespace StudentManagementSystem.Controllers
{
    [Authorize]

    public class TeacherController : Controller
    {
       
        private readonly ITeacherInterface _tb;
        public TeacherController( ITeacherInterface tb)
        {
            _tb = tb;
        }
        [HttpGet]   
        public IActionResult Index()
        {
            var allteacher = _tb.GetAllTeachers();
            return View(allteacher);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Teacher obj)
        {
            if (ModelState.IsValid)
            {
                _tb.Create(obj);
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {       
            var teacher = _tb.GetTeacher(id);

            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }
        [HttpPost]
        [ActionName("Edit")]
        public IActionResult Edit(Teacher teacher)
        {

            if (ModelState.IsValid)
            {
                _tb.Create(teacher);
                return RedirectToAction("Index");
            }
            return View(teacher);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {

            var teacher = _tb.GetTeacher(id);

            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConform(int id)
        {
          
            _tb.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

StudentManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container mt-5 mb-3">
    <div class="row">
        <div class="col-md-4">
            <div class="card p-3 mb-2">
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center">
                        <div class="icon"> <i class="bi bi-bucket-fill"></i> </div>
                        <div class="ms-2 c-details">
                            <h6 class="mb-0">Student</h6>
                        </div>
                    </div>
                </div>
                <div class="mt-5">
                    <h3 class="heading">You can do tasks like<br>Edit-Delete-Add-View</h3>
                    <a class="btn btn-primary" href="@Url.Action("Index", "Student")">Student Details</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card p-3 mb-2">
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center">
                        <div class="icon"> <i class="bi bi-person-circle"></i> </div>
                        <div class="ms-2 c-details">
                            <h6 class="mb-0">Teacher</h6>
                        </div>
                    </div>
                </div>
                <div class="mt-5">
                    <h3 class="heading">You can do tasks like<br>Edit-Delete-Add-View</h3>

                    <a class="btn btn-primary" href="@Url.Action("Index", "Teacher")">Teacher Details</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card p-3 mb-2">
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center">
                        <div class="icon"> <i class="bi bi-box"></i> </div>
                        <div class="ms-2 c-details">
                            <h6 class="mb-0">Cources</h6>
                        </div>
                    </div>
                </div>
                <div class="mt-5">
                    <h3 class="heading">You can do tasks like<br>Edit-Delete-Add-View</h3>
                    <a class="btn btn-primary" href="@Url.Action("Index", "Cources")">Cources Details</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card p-3 mb-2">
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center">
                        <div class="icon"> <i class="bi bi-box"></i> </div>
                        <div class="ms-2 c-details">
                            <h6 class="mb-3">Faculty</h6>
                        </div>
                    </div>
                </div>
                <div class="mt-5">
                    <h3 class="heading">You can do tasks like<br>Edit-Delete-Add-View</h3>
                    <a class="btn btn-primary" href="@Url.Action("Index", "Faculty")">Faculty Details</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card p-3 mb-2">
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center">
                        <div class="icon"> <i class="bi bi-box"></i> </div>
                        <div class="ms-2 c-details">
                            <h6 class="mb-3">ChosenCources</h6>
                        </div>
                    </div>
                </div>
                <div class="mt-5">
                    <h3 class="heading">You can do tasks like<br>Edit-Delete-Add-View</h3>
                    <a class="btn btn-primary" href="@Url.Action("Index", "ChosenCources")">ChoesnCource Details</a>
                </div>
            </div>
        </div>
    </div>
</div>